"""
BLIP3o Long-Caption WebDataset reader for JiT-half T2I training.

Data format:
  blip3o_long/sa_{000000..002890}.tar
    each tar: {id}.jpg + {id}.txt  (~11183 pairs per tar)
    jpg: JPEG image (~50KB avg)
    txt: long caption (~500 chars) generated by Qwen2.5-VL-7B-Instruct

Output per sample:
  img: uint8 Tensor (3, 256, 256) — matching ImageFolder output
  caption: str

Usage:
    from ldm_is_ae.data.blip3o import BLIP3oLongDataset
    ds = BLIP3oLongDataset(tar_dir='/path/to/blip3o_long')
    loader = DataLoader(ds, batch_size=4, num_workers=2)
    for img, caption in loader:
        ...
"""

import os, sys, io, glob, random, tarfile
from PIL import Image
import torch
from torch.utils.data import IterableDataset, DataLoader
from torchvision import transforms


from ldm_is_ae.utils.crop import center_crop_arr


class BLIP3oLongDataset(IterableDataset):
    """
    Stream tar files from BLIP3o-Pretrain-Long-Caption.
    Yields (img_tensor, caption_str) where img_tensor is uint8 (3, H, W).
    """

    def __init__(
        self,
        tar_dir,
        image_size=256,
        shuffle=True,
        max_tars=None,
        rank=0,
        world_size=1,
    ):
        super().__init__()
        self.tar_dir = tar_dir
        self.image_size = image_size
        self.shuffle = shuffle

        # Gather .tar files
        tar_files = sorted(glob.glob(os.path.join(tar_dir, '*.tar')))
        if not tar_files:
            raise FileNotFoundError(f"No .tar files found in {tar_dir}")
        if max_tars is not None:
            tar_files = tar_files[:max_tars]

        # Distributed partitioning: each rank gets the same number of tars
        tars_per_rank = len(tar_files) // world_size
        start = rank * tars_per_rank
        self.tar_files = tar_files[start:start + tars_per_rank]

        # Count actual images in assigned tars for accurate __len__
        self._len = 0
        for tar_path in self.tar_files:
            try:
                with tarfile.open(tar_path) as tar:
                    self._len += sum(1 for m in tar.getmembers() if m.name.endswith('.jpg'))
            except Exception:
                continue

    def __len__(self):
        return self._len

    def __iter__(self):
        tar_files = list(self.tar_files)
        if self.shuffle:
            random.shuffle(tar_files)

        for tar_path in tar_files:
            try:
                with tarfile.open(tar_path) as tar:
                    members = {m.name: m for m in tar.getmembers()}

                    jpg_keys = sorted(
                        k for k in members if k.endswith('.jpg')
                    )
                    if self.shuffle:
                        random.shuffle(jpg_keys)

                    for jpg_key in jpg_keys:
                        txt_key = jpg_key.rsplit('.', 1)[0] + '.txt'
                        if txt_key not in members:
                            continue

                        try:
                            # Read image
                            f = tar.extractfile(members[jpg_key])
                            pil_image = Image.open(
                                io.BytesIO(f.read())
                            ).convert('RGB')

                            # Read caption
                            f = tar.extractfile(members[txt_key])
                            caption = f.read().decode('utf-8').strip()

                            # Apply transforms
                            pil_image = center_crop_arr(
                                pil_image, self.image_size
                            )
                            if self.shuffle and random.random() < 0.5:
                                pil_image = pil_image.transpose(
                                    Image.FLIP_LEFT_RIGHT
                                )

                            img_tensor = transforms.PILToTensor()(pil_image)

                            yield img_tensor, caption

                        except Exception as e:
                            continue

            except Exception as e:
                print(f"Skipping tar {tar_path}: {e}")
                continue


if __name__ == '__main__':
    # Point BLIP3O_TAR_DIR at the extracted blip3o_long/ folder, or drop a copy here.
    TAR_DIR = os.environ.get('BLIP3O_TAR_DIR', './blip3o_long')

    if not os.path.isdir(TAR_DIR):
        print(f"Data directory not found: {TAR_DIR}")
        sys.exit(1)

    print(f"Using data: {TAR_DIR}")

    ds = BLIP3oLongDataset(
        tar_dir=TAR_DIR,
        image_size=256,
        shuffle=True,
        max_tars=3,
    )
    print(f"Total tars (limited to 3): {len(ds)}")

    loader = DataLoader(ds, batch_size=4, num_workers=2)

    for step, (imgs, captions) in enumerate(loader):
        if step >= 10:
            break
        print(
            f"[Step {step:2d}] "
            f"imgs={imgs.shape} dtype={imgs.dtype} "
            f"min={imgs.min().item():3d} max={imgs.max().item():3d} "
            f"cap[0]={captions[0][:80]}"
        )

    print("\n✅ BLIP3oLongDataset works correctly")
    print(f"   Total batches in 3 tars: {step + 1}")
